import type { ThemeDefinition } from "./types";

export const ANH_COLORS = {
  primary: "#1a1a1a",
  primaryLight: "#333333",
  secondary: "#ff8c00",
  accent: "#ffe600",
  red: "#e8381a",
  danger: "#C0392B",
  warning: "#E67E22",
  success: "#27AE60",
  background: "#F4F7FA",
  surface: "#FFFFFF",
  border: "#D8E2EC",
  text: "#1A2B3C",
  textMuted: "#5A6B7D",
};

export const THEMES: ThemeDefinition[] = [
  {
    id: "tema",
    title: "Tipo de registro",
    description: "Indique si el pozo se mantiene, se crea o se modifica en el AVM.",
    fields: [
      {
        key: "pozo_existente_avm",
        label: "¿Pozo existente en AVM ANH?",
        type: "select",
        catalogKey: "pozo_existente_avm",
        required: true,
      },
    ],
  },
  {
    id: "avm",
    title: "Información AVM",
    description: "Datos de operadora, contrato, campo petrolero (AVM) y formaciones según el AVM de la ANH.",
    fields: [
      { key: "operadora", label: "Operadora", type: "select", catalogKey: "operadoras", required: true },
      { key: "contrato", label: "Contrato según AVM ANH", type: "select", catalogKey: "contratos", required: true },
      { key: "campo_avm", label: "Campo AVM", type: "select", catalogKey: "campos_avm", required: true },
      { key: "pozo_formacion_avm", label: "Pozo formación AVM", type: "text", required: false },
      { key: "pozo_avm", label: "Pozo AVM", type: "text", required: false },
      { key: "formacion_avm", label: "Formación AVM", type: "text", required: false },
    ],
  },
  {
    id: "formaciones",
    title: "Formaciones y yacimientos (otras fuentes)",
    description: "Formaciones y yacimientos según FORMA 9SH y RUTY.",
    fields: [
      { key: "formacion_forma_9sh", label: "Formación FORMA 9SH", type: "text" },
      { key: "formacion_ruty", label: "Formación RUTY", type: "select", catalogKey: "formaciones_ruty" },
      { key: "yacimiento_ruty", label: "Yacimiento RUTY", type: "select", catalogKey: "yacimientos_ruty" },
    ],
  },
  {
    id: "general",
    title: "Información general del pozo",
    description: "Clasificación técnica, UWI y estado operativo del pozo.",
    fields: [
      { key: "tipo_angulo", label: "Tipo de pozo por ángulo", type: "select", catalogKey: "tipo_angulo" },
      { key: "tipo_trayectoria", label: "Tipo de pozo por trayectoria", type: "select", catalogKey: "tipo_trayectoria" },
      { key: "tipo_objetivo", label: "Tipo de pozo (según objetivo)", type: "select", catalogKey: "tipo_objetivo" },
      { key: "tipo_terminacion", label: "Tipo de terminación", type: "select", catalogKey: "tipo_terminacion" },
      { key: "sistema_levantamiento", label: "Sistema de levantamiento", type: "select", catalogKey: "sistema_levantamiento" },
      { key: "clasificacion_lahee", label: "Clasificación Lahee final", type: "text" },
      { key: "nombre_pozo_forma_6cr", label: "Nombre pozo FORMA 6CR", type: "text" },
      { key: "nombre_pozo_sgc", label: "Nombre pozo (SGC)", type: "text", required: true },
      { key: "uwi_sgc", label: "UWI (SGC)", type: "text" },
      { key: "uwi_fiscalizado", label: "UWI fiscalizado (generado)", type: "readonly" },
      { key: "estado_pozo", label: "Estado del pozo", type: "select", catalogKey: "estado_pozo", required: true },
    ],
  },
  {
    id: "ubicacion",
    title: "Ubicación del pozo",
    description: "Departamento, municipio, locación-clúster y coordenadas.",
    fields: [
      { key: "departamento", label: "Departamento", type: "select", catalogKey: "departamentos", required: true },
      { key: "municipio", label: "Municipio", type: "select", catalogKey: "municipios", required: true },
      { key: "codigo_dane_depto", label: "Código DANE departamento", type: "readonly" },
      { key: "codigo_dane_muni", label: "Código DANE municipio", type: "readonly" },
      { key: "locacion_cluster", label: "Locación-clúster", type: "text" },
      { key: "coord_bogota_x", label: "Coordenada superficie X (Bogotá)", type: "coordinate" },
      { key: "coord_bogota_y", label: "Coordenada superficie Y (Bogotá)", type: "coordinate" },
      { key: "coord_nacional_x", label: "Coordenada superficie X (Nacional)", type: "coordinate" },
      { key: "coord_nacional_y", label: "Coordenada superficie Y (Nacional)", type: "coordinate" },
      { key: "longitud", label: "Longitud", type: "coordinate", placeholder: "-gg,gggggg" },
      { key: "latitud", label: "Latitud", type: "coordinate", placeholder: "+/-gg,gggggg" },
    ],
  },
  {
    id: "produccion",
    title: "Producción",
    description: "Acumulados de producción del pozo.",
    fields: [
      { key: "prod_dias", label: "Días acumulados", type: "number" },
      { key: "prod_petroleo", label: "Petróleo acumulado (BBL)", type: "number" },
      { key: "prod_agua", label: "Agua acumulada (BBL)", type: "number" },
      { key: "prod_gas", label: "Gas acumulado (KPC)", type: "number" },
    ],
  },
  {
    id: "inyeccion",
    title: "Inyección",
    description: "Acumulados de inyección del pozo.",
    fields: [
      { key: "iny_dias", label: "Días acumulados", type: "number" },
      { key: "iny_agua", label: "Agua acumulada (BBL)", type: "number" },
      { key: "iny_gas", label: "Gas acumulado (KPC)", type: "number" },
      { key: "iny_otros", label: "Otros acumulado", type: "number" },
    ],
  },
];

export const EXCEL_COLUMN_MAP: Record<string, keyof import("./types").WellRecord> = {
  "POZO EXISTENTE EN AVM ANH?": "pozo_existente_avm",
  OPERADORA: "operadora",
  "CONTRATO SEGÚN AVM ANH": "contrato",
  "CAMPO AVM": "campo_avm",
  "POZO FORMACION AVM": "pozo_formacion_avm",
  "POZO AVM": "pozo_avm",
  "FORMACION AVM": "formacion_avm",
  "FORMACIÓN FORMA 9SH": "formacion_forma_9sh",
  "FORMACIÓN RUTY": "formacion_ruty",
  "YACIMIENTO RUTY": "yacimiento_ruty",
  "TIPO DE POZO POR ANGULO": "tipo_angulo",
  "TIPO DE POZO POR TRAYECTORIA": "tipo_trayectoria",
  "TIPO DE POZO (SEGUN OBJETIVO)": "tipo_objetivo",
  "TIPO DE TERMINACIÓN": "tipo_terminacion",
  "SISTEMA DE LEVANTAMENTO": "sistema_levantamiento",
  "CLASIFICACIÓN LAHEE FINAL": "clasificacion_lahee",
  "NOMBRE POZO FORMA 6CR": "nombre_pozo_forma_6cr",
  "UWI (SGC)": "uwi_sgc",
  "NOMBRE POZO (SGC)": "nombre_pozo_sgc",
  "ESTADO DEL POZO": "estado_pozo",
  DEPARTAMENTO: "departamento",
  MUNICIPIO: "municipio",
  "CODIGO DANE DEPARTAMENTO": "codigo_dane_depto",
  "CODIGO DANE MUNICIPIO": "codigo_dane_muni",
  "LOCACIÓN-CLUSTER": "locacion_cluster",
  "DIAS ACUMULADOS": "prod_dias",
  "PETRÓLEO ACUMULADO  (BBL)": "prod_petroleo",
  "AGUA ACUMULADA (BBL)": "prod_agua",
  "GAS ACUMULADO  (KPC)": "prod_gas",
};
