// <auto-generated />
using System;
using Anh.Vip.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anh.Vip.Infrastructure.Migrations
{
    [DbContext(typeof(VipDbContext))]
    partial class VipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Anh.Vip.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("action");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("actor_email");

                    b.Property<string>("AfterJson")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("before_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("entity_type");

                    b.HasKey("Id");

                    b.ToTable("audit_log", "vip");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.CatDepartamento", b =>
                {
                    b.Property<string>("CodigoDane")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("codigo_dane");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("nombre");

                    b.HasKey("CodigoDane");

                    b.ToTable("cat_departamento", "vip");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.CatListaValor", b =>
                {
                    b.Property<string>("Catalogo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("catalogo");

                    b.Property<string>("Valor")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("valor");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.HasKey("Catalogo", "Valor");

                    b.HasIndex("Catalogo");

                    b.ToTable("cat_lista_valor", "vip");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.CatMunicipio", b =>
                {
                    b.Property<string>("CodigoDane")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("codigo_dane");

                    b.Property<string>("CodigoDaneDepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("codigo_dane_depto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("nombre");

                    b.HasKey("CodigoDane");

                    b.HasIndex("CodigoDaneDepto");

                    b.ToTable("cat_municipio", "vip");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.Notebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveVersionId")
                        .HasColumnType("int")
                        .HasColumnName("active_version_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("created_by");

                    b.Property<string>("Operadora")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("operadora");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("submitted_by");

                    b.Property<int?>("SubmittedVersionId")
                        .HasColumnType("int")
                        .HasColumnName("submitted_version_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActiveVersionId");

                    b.HasIndex("SubmittedVersionId");

                    b.ToTable("notebooks", "vip");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.NotebookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("actor_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("event_type");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("message");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_json");

                    b.Property<int>("NotebookId")
                        .HasColumnType("int")
                        .HasColumnName("notebook_id");

                    b.Property<int?>("UploadId")
                        .HasColumnType("int")
                        .HasColumnName("upload_id");

                    b.HasKey("Id");

                    b.HasIndex("NotebookId");

                    b.ToTable("notebook_events", "vip");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.Upload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("ErrorIssues")
                        .HasColumnType("int")
                        .HasColumnName("error_issues");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("filename");

                    b.Property<int>("InfoIssues")
                        .HasColumnType("int")
                        .HasColumnName("info_issues");

                    b.Property<int>("InvalidRecords")
                        .HasColumnType("int")
                        .HasColumnName("invalid_records");

                    b.Property<int?>("NotebookId")
                        .HasColumnType("int")
                        .HasColumnName("notebook_id");

                    b.Property<string>("Operadora")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("operadora");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("submitted_by");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int")
                        .HasColumnName("total_records");

                    b.Property<int>("ValidRecords")
                        .HasColumnType("int")
                        .HasColumnName("valid_records");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int")
                        .HasColumnName("version_number");

                    b.Property<int>("WarningIssues")
                        .HasColumnType("int")
                        .HasColumnName("warning_issues");

                    b.Property<int>("WarningRecords")
                        .HasColumnType("int")
                        .HasColumnName("warning_records");

                    b.HasKey("Id");

                    b.HasIndex("NotebookId");

                    b.ToTable("uploads", "vip");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("email");

                    b.Property<string>("Operadora")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("operadora");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "vip");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.ValidationIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("field");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("rule");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("severity");

                    b.Property<int>("WellId")
                        .HasColumnType("int")
                        .HasColumnName("well_id");

                    b.HasKey("Id");

                    b.HasIndex("WellId");

                    b.ToTable("validation_issues", "vip");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.Well", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampoAvm")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("campo_avm");

                    b.Property<string>("ClasificacionLahee")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("clasificacion_lahee");

                    b.Property<string>("CodigoDaneDepto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("codigo_dane_depto");

                    b.Property<string>("CodigoDaneMuni")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("codigo_dane_muni");

                    b.Property<string>("Contrato")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("contrato");

                    b.Property<string>("CoordBogotaX")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("coord_bogota_x");

                    b.Property<string>("CoordBogotaY")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("coord_bogota_y");

                    b.Property<string>("CoordNacionalX")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("coord_nacional_x");

                    b.Property<string>("CoordNacionalY")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("coord_nacional_y");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Departamento")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("departamento");

                    b.Property<string>("EstadoPozo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("estado_pozo");

                    b.Property<string>("FormacionAvm")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("formacion_avm");

                    b.Property<string>("FormacionForma9sh")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("formacion_forma_9sh");

                    b.Property<string>("FormacionRuty")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("formacion_ruty");

                    b.Property<string>("InyAgua")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("iny_agua");

                    b.Property<string>("InyDias")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("iny_dias");

                    b.Property<string>("InyGas")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("iny_gas");

                    b.Property<string>("InyOtros")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("iny_otros");

                    b.Property<string>("Latitud")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("latitud");

                    b.Property<string>("LocacionCluster")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("locacion_cluster");

                    b.Property<string>("Longitud")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("longitud");

                    b.Property<string>("Municipio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("municipio");

                    b.Property<string>("NombrePozoForma6cr")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("nombre_pozo_forma_6cr");

                    b.Property<string>("NombrePozoSgc")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("nombre_pozo_sgc");

                    b.Property<string>("Operadora")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("operadora");

                    b.Property<string>("PozoAvm")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("pozo_avm");

                    b.Property<string>("PozoExistenteAvm")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("pozo_existente_avm");

                    b.Property<string>("PozoFormacionAvm")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("pozo_formacion_avm");

                    b.Property<string>("ProdAgua")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("prod_agua");

                    b.Property<string>("ProdDias")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("prod_dias");

                    b.Property<string>("ProdGas")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("prod_gas");

                    b.Property<string>("ProdPetroleo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("prod_petroleo");

                    b.Property<string>("SistemaLevantamiento")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("sistema_levantamiento");

                    b.Property<string>("TipoAngulo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("tipo_angulo");

                    b.Property<string>("TipoObjetivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("tipo_objetivo");

                    b.Property<string>("TipoTerminacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("tipo_terminacion");

                    b.Property<string>("TipoTrayectoria")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("tipo_trayectoria");

                    b.Property<int?>("UploadId")
                        .HasColumnType("int")
                        .HasColumnName("upload_id");

                    b.Property<string>("UwiFiscalizado")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("uwi_fiscalizado");

                    b.Property<string>("UwiSgc")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("uwi_sgc");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("validation_status");

                    b.Property<string>("YacimientoRuty")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("yacimiento_ruty");

                    b.HasKey("Id");

                    b.HasIndex("UploadId");

                    b.ToTable("wells", "vip");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.CatMunicipio", b =>
                {
                    b.HasOne("Anh.Vip.Domain.Entities.CatDepartamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("CodigoDaneDepto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.Notebook", b =>
                {
                    b.HasOne("Anh.Vip.Domain.Entities.Upload", null)
                        .WithMany()
                        .HasForeignKey("ActiveVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Anh.Vip.Domain.Entities.Upload", null)
                        .WithMany()
                        .HasForeignKey("SubmittedVersionId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.NotebookEvent", b =>
                {
                    b.HasOne("Anh.Vip.Domain.Entities.Notebook", "Notebook")
                        .WithMany("Events")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Notebook");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.Upload", b =>
                {
                    b.HasOne("Anh.Vip.Domain.Entities.Notebook", "Notebook")
                        .WithMany("Uploads")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Notebook");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.ValidationIssue", b =>
                {
                    b.HasOne("Anh.Vip.Domain.Entities.Well", "Well")
                        .WithMany("Issues")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.Well", b =>
                {
                    b.HasOne("Anh.Vip.Domain.Entities.Upload", "Upload")
                        .WithMany("Wells")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.CatDepartamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.Notebook", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.Upload", b =>
                {
                    b.Navigation("Wells");
                });

            modelBuilder.Entity("Anh.Vip.Domain.Entities.Well", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
